### ISSUE TITLE
важная ошибка...

### ISSUE THREAD

**Issue by floppa-coder** [Ochpochmaks/Larnos-Planet#5]
положи содержимое зип файла в мод.

**Comment by Ochpochmaks** [comment]
Я не понял как это сделать, если можешь, объясни пожалуйста, заранее спасибо если объяснишь

**Comment by floppa-coder** [comment]
1: положи содержимое зип файла в папку.
2: из этой папки убери mod.json и README.md.
3: содержимое папки в мод
