### ISSUE TITLE
Ошибка, нету руд (исправлено)

### ISSUE THREAD

**Issue by RouterXdd** [Ochpochmaks/Larnos-Planet#6]
Where ore tiles, genius?

**Comment by Ochpochmaks** [comment]
Всмысле? Названия руд есть, названия всего в этом моде есть, чего нету?

**Comment by RouterXdd** [comment]
САМИХ РУД
![Снимок экрана 2024-02-25 191022](https://github.com/Ochpochmaks/Larnos-Planet/assets/91018607/3224096b-b83c-43fe-a914-1b3ee21a6575)

**Comment by Ochpochmaks** [comment]
Странно, у меня в моде есть, сейчас перепроверю файлы на гитхабе (извини за долгое ожидание)

**Comment by Ochpochmaks** [comment]
Добавил руды, опять же извини за мою невнимательность
